AllCops:
  TargetRubyVersion: 2.5.0
  Exclude:
    - 'lib/relax-color.rb'
    - 'spec/spec_helper.rb'
    - 'test/*'
    - '_test_as_a_gem/*'

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true